# Site settings
title: Kate's Blog
header-img: img/home-bg.png
email: kate@flatironschool.com
copyright_name: ktravers
description: > # this means to ignore newlines until "baseurl:"
  a really cool blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: kttravers
github_username:  ktravers
learn_profile: ktravers
email_username: kate@flatironschool.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
