# Name of your site (displayed in the header)
name: Kate Travers

# Short bio or description (displayed in the header)
description: bro(ad)grammer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/8152930

# Includes an icon in the footer for each username you enter
footer-links:
  email: kate@kate-travers.com
  facebook:
  github: ktravers
  instagram:
  linkedin: kttravers
  rss:
  twitter: kttravers
  stackoverflow: users/3880374/ktravers

# Your disqus shortname, entering this will enable commenting on posts
disqus: kttravers

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-17583145-6

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://kate-travers.com

# If you're hosting your site at a Project repository on GitHub pages (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io) then add in the baseurl here, like this: "/repository-name"
baseurl: ""

collections:
  posts:
    output: true
    permalink: /blog/:collection/:title

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
